language: generic

services:
  - docker

env:
  - IN_TRAVIS=true

script:
  - make tc build

deploy:
  provider: releases
  # https://github.com/settings/tokens
  # Add variable TOKEN in TravisCI settings
  api_key: $TOKEN
  file:
    - "thesis.pdf"
    - "report.pdf"
  name: Build $(date +'%d.%m.%Y %R')
  skip-cleanup: true
